language: php
dist: bionic
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "7.2"
      env: TYPO3_VERSION=^9 RUN_SONAR_SCANNER=1
    - php: "7.3"
      env: TYPO3_VERSION=^9

addons:
  sonarcloud:
    token:
      secure: "OMN3L740UOjz6MTy+9jkbfxTABECgYXAXW50vlMJHMrUv9b4s12WNFzLF53WBuh7NI8MfY/YLST+E1mopQeCezFf5qJOt+IAiaB/x4zQK4noxIRM2mgbvy5yFtQP4S46UUOwWOsFB9t+foU+m6IoByJVDnF0AsbLny2LcFdKHIHs4ejgtgLY0m83lxOkC7IToW94lSmQyBo8TCdF2UV/mzxU/LZblDXnMj0PJwom7FgGJ8Go3m8Pk9DGgE/0bO02oa5kqQyv6s9vMiLAg2LaToZrbPv5RqqzGh+6SSUoB0cEcA9or7XcJSHrICjmp05MTTeg56q6aNhFy31paC4Q8xEincZ5h3VxjnYDGoOUWSOxmCVsSbbOhM8KY7oQk3FfocxfTvgNiJJIEKkXgKkNaEGsl9VlQydVDQPMbgR5bcnh4O0zD4F1baHo8w/SaqX31ABHbGGV0WaEwVLjc9m6C4/xhoZULInx8XrwVigweVehn8reBWfmjT6Z4w6hQ3yr8qP89nZl2oQwlBAvFxa9Nl5hJ8zpMjyyPSrpBbLxqzVD23pz+3y4xfBG8Oy9QQMLWQvhvGqGw88trI6I405DjQkM3RRWYuNuKdUaGUFP89Vstw184zeuKE6sO/wTon30TtmaOhhigrgIreOAdCVwettHYXI/f1vVyzyu5UZpK3o="

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms-core=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/web

script:
  - find . -name \*.php  ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} > /dev/null \;
  - if [[ $RUN_SONAR_SCANNER == "1" ]]; then sonar-scanner -Dsonar.projectVersion=$TRAVIS_TAG; fi
