services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterData\:
    resource: '../Classes/*'

  Brotkrueml\JobRouterData\Command\SyncCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:sync'
        schedulable: true

  Brotkrueml\JobRouterData\Command\TransmitCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:transmit'
        schedulable: true

  Brotkrueml\JobRouterData\Command\CleanUpTransfersCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:cleanuptransfers'
        schedulable: true

  Brotkrueml\JobRouterData\EventListener\ToolbarItemProvider:
    tags:
      - name: event.listener
        identifier: 'jobrouter-process/toolbar-item-provider'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
