services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterData\:
    resource: '../Classes/*'

  querybuilder.tx_jobrouterdata_domain_model_transfer:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_jobrouterdata_domain_model_transfer'

  Brotkrueml\JobRouterData\Command\CleanUpTransfersCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:cleanuptransfers'
        schedulable: true

  Brotkrueml\JobRouterData\Command\SyncCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:sync'
        schedulable: true

  Brotkrueml\JobRouterData\Command\TransmitCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:transmit'
        schedulable: true

  Brotkrueml\JobRouterData\EventListener\ToolbarItemProvider:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/toolbar-item-provider'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent

  Brotkrueml\JobRouterData\Transfer\Deleter:
    arguments:
      - '@querybuilder.tx_jobrouterdata_domain_model_transfer'
